# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-11-18 12:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_auto_20201118_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2020, 11, 18, 15, 19, 27, 508540), verbose_name='Дата'),
        ),
    ]
