# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-11-19 15:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0028_auto_20201119_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2020, 11, 19, 18, 26, 25, 959423), verbose_name='Дата'),
        ),
    ]
