# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-22 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='quantity_1',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
