# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-27 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_orderitem_quantity_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='street',
            field=models.CharField(default='s', max_length=100),
        ),
    ]
