# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-29 11:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20201029_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='user_id',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
