# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-11-13 12:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0010_remove_orderitem_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_man',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='Pokupatel', to=settings.AUTH_USER_MODEL),
        ),
    ]
