# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-11-13 12:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_order_order_man'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_man',
        ),
    ]
